version: "3.8"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    # Note redundant variables will get overriden as `environment` takes precedence.
    # We currently override the `DATABASE_URL` as the host differs from when MySQL
    # is installed/running system wide.
    environment:
      - DATABASE_URL=mysql://issa:ortouc@database:3306/test?serverVersion=5.7
    depends_on:
      - database
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
